### ISSUE TITLE
Typescript type error on constructor in example

### ISSUE THREAD

**Issue by SC4RECOIN** [miguelmota/merkletreejs#12]
Your example in the README throws an error in typescript on the constructor.
```Argument of type 'WordArray[]' is not assignable to parameter of type 'Buffer[]'```

**Comment by miguelmota** [comment]
@SC4RECOIN the typescript problems are now fixed in the latest release.

Thanks for reporting!

**Comment by anajuliabit** [comment]
HI @miguelmota, I'm still having this problem in version 0.2.31

**Comment by miguelmota** [comment]
Hi @anajuliabit, can you provide an example snippet? thanks!
